import { StyleSheet } from 'react-native';

export const exploreMapStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050816',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#050816',
    gap: 8,
  },
  searchTypeToggleButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: '#7c3aed',
    shadowColor: '#7c3aed',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#101936',
    borderRadius: 20,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: '#F8FAFC',
  },
  searchButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4,
  },
  filterSection: {
    backgroundColor: '#050816',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 0,
  },
  filterButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filterButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    backgroundColor: '#101936',
    gap: 4,
    minHeight: 36,
  },
  filterButtonActive: {
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
  },
  filterButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#94A3B8',
  },
  filterButtonTextActive: {
    color: '#F8FAFC',
  },
  viewModeToggleButton: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    backgroundColor: '#101936',
  },
  dropdownContainer: {
    position: 'absolute',
    backgroundColor: '#101936',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    paddingVertical: 6,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  dropdownOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    marginHorizontal: 4,
    marginVertical: 1,
  },
  dropdownOptionActive: {
    backgroundColor: 'rgba(124, 58, 237, 0.1)',
  },
  dropdownOptionText: {
    fontSize: 14,
    color: '#94A3B8',
    fontWeight: '500',
  },
  dropdownOptionTextActive: {
    color: '#7c3aed',
    fontWeight: '600',
  },
  dropdownOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
  },
  mapContainer: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  map: {
    flex: 1,
  },
  locationButton: {
    position: 'absolute',
    bottom: 30,
    right: 16,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#7c3aed',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#7c3aed',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 12,
    borderWidth: 0,
    zIndex: 10,
  },
  listContainer: {
    flex: 1,
    backgroundColor: '#050816',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  talentCard: {
    flexDirection: 'row',
    backgroundColor: '#101936',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
  },
  talentAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 12,
  },
  talentInfo: {
    flex: 1,
  },
  talentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  talentName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#F8FAFC',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingIcon: {
    fontSize: 12,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#F8FAFC',
  },
  reviewCount: {
    fontSize: 11,
    color: '#94A3B8',
  },
  talentLocation: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 4,
  },
  talentBio: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 4,
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
    gap: 6,
  },
  skillBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7c3aed',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    gap: 6,
  },
  skillBadgeMatch: {
    backgroundColor: '#10b981',
    borderWidth: 1,
    borderColor: '#059669',
  },
  matchIndicator: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#F8FAFC',
  },
  skillText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#F8FAFC',
  },
  skillDivider: {
    fontSize: 11,
    color: '#E0E7FF',
  },
  priceText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#E0E7FF',
  },
  moreSkillsBadge: {
    backgroundColor: 'rgba(124, 58, 237, 0.3)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#7c3aed',
  },
  moreSkillsText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#7c3aed',
  },
  skillWithPrice: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(124, 58, 237, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  skillName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7c3aed',
  },
  skillPrice: {
    fontSize: 11,
    fontWeight: '500',
    color: '#94A3B8',
  },
  resultsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#050816',
    borderTopWidth: 1,
    borderTopColor: 'rgba(148, 163, 184, 0.25)',
  },
  resultsCount: {
    fontSize: 14,
    fontWeight: '700',
    color: '#F8FAFC',
  },
  resultsSubtext: {
    fontSize: 12,
    color: '#94A3B8',
  },
});
